[colors]
transparent_background_colors = true

[colors.primary]
background = "#000000"

[colors.normal]
black = "#000000"

[colors.bright]
black = "#000000"

[colors.dim]
black = "#000000"

[cursor]
vi_mode_style = "None"

[cursor.style]
blinking = "On"

[font.normal]
family = "Fira Code Nerd Font"

[scrolling]
history = 100000

[window]
opacity = 1.0

[window.dimensions]
columns = 130
lines = 30
